source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 3.0'
pod 'RealmSwift'
pod 'PagingMenuController'
pod 'LiquidFloatingActionButton’, :git => 'https://github.com/yoavlt/LiquidFloatingActionButton.git', :branch => 'swift-2.0'
pod 'ASAudioPlayer'